"""empty message

Revision ID: 41a42b3dbc64
Revises: 
Create Date: 2021-02-21 20:19:06.768413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41a42b3dbc64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extras',
    sa.Column('extras_id', sa.Integer(), nullable=False),
    sa.Column('valor_extra', sa.String(length=200), nullable=True),
    sa.Column('nombre_extra', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('extras_id')
    )
    op.create_table('horarios',
    sa.Column('horarios_id', sa.Integer(), nullable=False),
    sa.Column('fechas', sa.DateTime(), nullable=True),
    sa.Column('horas', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('horarios_id')
    )
    op.create_table('servicios',
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('nombre_servicio', sa.String(length=200), nullable=True),
    sa.Column('valor_servicio', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('servicio_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=200), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('servicios')
    op.drop_table('horarios')
    op.drop_table('extras')
    # ### end Alembic commands ###
