"""empty message

Revision ID: 4c0d4f696dc5
Revises: 98dcd9524cba
Create Date: 2021-02-21 22:18:43.665787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c0d4f696dc5'
down_revision = '98dcd9524cba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'agendamiento', 'servicios', ['f_servicios_id'], ['servicio_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agendamiento', type_='foreignkey')
    # ### end Alembic commands ###
