"""empty message

Revision ID: 6d4dbfea58b6
Revises: a7ace40788e7
Create Date: 2021-02-21 22:30:29.326783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4dbfea58b6'
down_revision = 'a7ace40788e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agendamiento', sa.Column('f_extras_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'agendamiento', 'servicios', ['f_servicios_id'], ['servicio_id'])
    op.create_foreign_key(None, 'agendamiento', 'extras', ['f_extras_id'], ['extras_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agendamiento', type_='foreignkey')
    op.drop_constraint(None, 'agendamiento', type_='foreignkey')
    op.drop_column('agendamiento', 'f_extras_id')
    # ### end Alembic commands ###
