"""empty message

Revision ID: 98dcd9524cba
Revises: 58e128ee0544
Create Date: 2021-02-21 22:06:16.213622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98dcd9524cba'
down_revision = '58e128ee0544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agendamiento', sa.Column('f_servicios_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'agendamiento', 'servicios', ['f_servicios_id'], ['servicio_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agendamiento', type_='foreignkey')
    op.drop_column('agendamiento', 'f_servicios_id')
    # ### end Alembic commands ###
