"""empty message

Revision ID: a7ace40788e7
Revises: 4c0d4f696dc5
Create Date: 2021-02-21 22:29:41.480598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7ace40788e7'
down_revision = '4c0d4f696dc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'agendamiento', 'servicios', ['f_servicios_id'], ['servicio_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agendamiento', type_='foreignkey')
    # ### end Alembic commands ###
